-- Auto-generated from apps/web/src/services/permission.service.ts DEFAULT_PERMISSIONS
-- Run this in Supabase SQL editor to seed the permissions dictionary.

-- Ensure schema is up to date (older databases may be missing these columns).
alter table permissions add column if not exists key text;
alter table permissions add column if not exists module text;
alter table permissions add column if not exists action text;
alter table permissions add column if not exists sort_order integer default 0;
alter table permissions add column if not exists description text;
alter table permissions add column if not exists group_name text;
update permissions set key = id where key is null;
create unique index if not exists permissions_key_unique on permissions(key);

insert into permissions (id, key, module, action, name, group_name, description, sort_order) values
  ('dashboard.view', 'dashboard.view', 'dashboard', 'view', 'Xem bảng điều khiển', 'Tổng quan', 'Truy cập trang Dashboard và các thẻ số liệu tổng quan', 1),
  ('dashboard.revenue.view', 'dashboard.revenue.view', 'dashboard', 'revenue.view', 'Xem doanh thu trên Dashboard', 'Tổng quan', 'Hiển thị số liệu doanh thu, doanh số trên Dashboard', 2),
  ('dashboard.profit.view', 'dashboard.profit.view', 'dashboard', 'profit.view', 'Xem lợi nhuận trên Dashboard', 'Tổng quan', 'Hiển thị số liệu lợi nhuận / giá vốn trên Dashboard (quyền nhạy cảm)', 3),
  ('pos.access', 'pos.access', 'pos', 'access', 'Truy cập màn hình POS', 'POS - Bán hàng', 'Mở màn hình bán hàng tại quầy', 4),
  ('pos.sell', 'pos.sell', 'pos', 'sell', 'Tạo đơn & thanh toán', 'POS - Bán hàng', 'Chọn hàng, thanh toán và chốt đơn tại quầy', 5),
  ('pos.price.override', 'pos.price.override', 'pos', 'price.override', 'Sửa giá bán tại quầy', 'POS - Bán hàng', 'Chỉnh giá bán của sản phẩm ngay trên màn hình POS', 6),
  ('pos.discount.apply', 'pos.discount.apply', 'pos', 'discount.apply', 'Áp dụng giảm giá', 'POS - Bán hàng', 'Áp dụng giảm giá theo % hoặc số tiền cho đơn POS', 7),
  ('pos.discount.approve', 'pos.discount.approve', 'pos', 'discount.approve', 'Duyệt giảm giá vượt ngưỡng', 'POS - Bán hàng', 'Phê duyệt phiếu giảm giá vượt ngưỡng cho phép của thu ngân', 8),
  ('pos.void_item', 'pos.void_item', 'pos', 'void_item', 'Hủy dòng sản phẩm trong đơn', 'POS - Bán hàng', 'Bỏ một dòng hàng khỏi đơn đang lập', 9),
  ('pos.cancel_order', 'pos.cancel_order', 'pos', 'cancel_order', 'Hủy đơn đang lập', 'POS - Bán hàng', 'Hủy bỏ toàn bộ đơn hàng đang lập tại quầy', 10),
  ('pos.refund', 'pos.refund', 'pos', 'refund', 'Hoàn tiền tại quầy', 'POS - Bán hàng', 'Thực hiện hoàn tiền cho khách ngay tại màn hình POS', 11),
  ('pos.print_receipt', 'pos.print_receipt', 'pos', 'print_receipt', 'In hóa đơn', 'POS - Bán hàng', 'In hoặc xuất hóa đơn cho khách sau khi chốt đơn', 12),
  ('pos.reprint_receipt', 'pos.reprint_receipt', 'pos', 'reprint_receipt', 'In lại hóa đơn cũ', 'POS - Bán hàng', 'In lại hóa đơn cho đơn hàng đã hoàn tất', 13),
  ('shifts.view', 'shifts.view', 'shifts', 'view', 'Xem ca làm việc', 'Ca làm việc', 'Xem danh sách ca làm và lịch sử mở/đóng ca', 14),
  ('shifts.open', 'shifts.open', 'shifts', 'open', 'Mở ca làm việc', 'Ca làm việc', 'Tạo phiên ca mới với số dư đầu ca', 15),
  ('shifts.close', 'shifts.close', 'shifts', 'close', 'Đóng ca làm việc', 'Ca làm việc', 'Chốt số liệu cuối ca và nộp tiền quầy', 16),
  ('shifts.cash_in', 'shifts.cash_in', 'shifts', 'cash_in', 'Thu tiền vào quầy', 'Ca làm việc', 'Ghi nhận thu tiền mặt phát sinh trong ca', 17),
  ('shifts.cash_out', 'shifts.cash_out', 'shifts', 'cash_out', 'Chi tiền từ quầy', 'Ca làm việc', 'Ghi nhận chi tiền mặt phát sinh trong ca', 18),
  ('shifts.adjust', 'shifts.adjust', 'shifts', 'adjust', 'Điều chỉnh chênh lệch quỹ', 'Ca làm việc', 'Quyền duyệt chênh lệch số tiền cuối ca (quyền nhạy cảm)', 19),
  ('products.view', 'products.view', 'products', 'view', 'Xem danh sách sản phẩm', 'Sản phẩm', 'Xem danh sách sản phẩm trong hệ thống', 20),
  ('products.detail.view', 'products.detail.view', 'products', 'detail.view', 'Xem chi tiết sản phẩm', 'Sản phẩm', 'Xem trang chi tiết của một sản phẩm', 21),
  ('products.create', 'products.create', 'products', 'create', 'Tạo sản phẩm mới', 'Sản phẩm', 'Thêm sản phẩm mới vào danh mục', 22),
  ('products.update', 'products.update', 'products', 'update', 'Cập nhật sản phẩm', 'Sản phẩm', 'Chỉnh sửa thông tin sản phẩm có sẵn', 23),
  ('products.delete', 'products.delete', 'products', 'delete', 'Xóa sản phẩm', 'Sản phẩm', 'Xóa sản phẩm khỏi hệ thống (quyền nhạy cảm)', 24),
  ('products.import', 'products.import', 'products', 'import', 'Nhập sản phẩm từ Excel', 'Sản phẩm', 'Tải lên file Excel/CSV để thêm hàng loạt sản phẩm', 25),
  ('products.export', 'products.export', 'products', 'export', 'Xuất sản phẩm ra Excel', 'Sản phẩm', 'Xuất danh sách sản phẩm ra file Excel/CSV', 26),
  ('products.price.update', 'products.price.update', 'products', 'price.update', 'Cập nhật giá bán', 'Sản phẩm', 'Thay đổi giá bán của sản phẩm', 27),
  ('products.cost.view', 'products.cost.view', 'products', 'cost.view', 'Xem giá vốn', 'Sản phẩm', 'Xem giá vốn / giá nhập của sản phẩm (quyền nhạy cảm)', 28),
  ('products.cost.update', 'products.cost.update', 'products', 'cost.update', 'Cập nhật giá vốn', 'Sản phẩm', 'Thay đổi giá vốn / giá nhập của sản phẩm (quyền nhạy cảm)', 29),
  ('products.barcode.scan', 'products.barcode.scan', 'products', 'barcode.scan', 'Quét mã vạch', 'Sản phẩm', 'Quét mã vạch sản phẩm', 291),
  ('products.barcode.generate', 'products.barcode.generate', 'products', 'barcode.generate', 'Tạo mã vạch', 'Sản phẩm', 'Tự động tạo mã vạch cho sản phẩm', 292),
  ('products.barcode.update', 'products.barcode.update', 'products', 'barcode.update', 'Cập nhật mã vạch', 'Sản phẩm', 'Cập nhật mã vạch cho sản phẩm / phiên bản', 293),
  ('products.barcode.print', 'products.barcode.print', 'products', 'barcode.print', 'In tem mã vạch', 'Sản phẩm', 'In tem nhãn mã vạch cho sản phẩm', 294),
  ('categories.view', 'categories.view', 'categories', 'view', 'Xem danh mục sản phẩm', 'Danh mục', 'Xem danh sách danh mục sản phẩm', 30),
  ('categories.create', 'categories.create', 'categories', 'create', 'Tạo danh mục mới', 'Danh mục', 'Thêm danh mục sản phẩm mới', 31),
  ('categories.update', 'categories.update', 'categories', 'update', 'Cập nhật danh mục', 'Danh mục', 'Chỉnh sửa tên / cấu trúc danh mục', 32),
  ('categories.delete', 'categories.delete', 'categories', 'delete', 'Xóa danh mục', 'Danh mục', 'Xóa danh mục khỏi hệ thống', 33),
  ('inventory.view', 'inventory.view', 'inventory', 'view', 'Xem tồn kho', 'Tồn kho', 'Xem số lượng tồn theo từng chi nhánh', 34),
  ('inventory.history.view', 'inventory.history.view', 'inventory', 'history.view', 'Xem lịch sử nhập / xuất kho', 'Tồn kho', 'Xem toàn bộ phát sinh nhập xuất kho', 35),
  ('inventory.adjust', 'inventory.adjust', 'inventory', 'adjust', 'Điều chỉnh tồn kho', 'Tồn kho', 'Tăng / giảm tồn thủ công kèm lý do (quyền nhạy cảm)', 36),
  ('inventory.transfer', 'inventory.transfer', 'inventory', 'transfer', 'Chuyển kho giữa chi nhánh', 'Tồn kho', 'Tạo phiếu chuyển kho qua lại giữa các chi nhánh', 37),
  ('inventory.audit', 'inventory.audit', 'inventory', 'audit', 'Kiểm kê kho', 'Tồn kho', 'Tạo phiếu kiểm kê và cân đối tồn', 38),
  ('inventory.threshold.manage', 'inventory.threshold.manage', 'inventory', 'threshold.manage', 'Cấu hình tồn kho tối thiểu', 'Tồn kho', 'Thiết lập định mức cảnh báo tồn kho cho từng sản phẩm', 39),
  ('inventory.import', 'inventory.import', 'inventory', 'import', 'Nhập tồn từ file', 'Tồn kho', 'Nhập tồn kho ban đầu từ file Excel/CSV', 40),
  ('inventory.export', 'inventory.export', 'inventory', 'export', 'Xuất tồn kho ra Excel', 'Tồn kho', 'Xuất số liệu tồn kho ra file', 41),
  ('orders.view', 'orders.view', 'orders', 'view', 'Xem danh sách hóa đơn', 'Đơn hàng', 'Xem danh sách hóa đơn đã chốt', 42),
  ('orders.detail.view', 'orders.detail.view', 'orders', 'detail.view', 'Xem chi tiết hóa đơn', 'Đơn hàng', 'Xem chi tiết dòng hàng / thanh toán của hóa đơn', 43),
  ('orders.create', 'orders.create', 'orders', 'create', 'Tạo hóa đơn ngoài quầy', 'Đơn hàng', 'Tạo hóa đơn từ trang quản lý đơn (không qua POS)', 44),
  ('orders.update', 'orders.update', 'orders', 'update', 'Cập nhật hóa đơn', 'Đơn hàng', 'Chỉnh sửa thông tin / dòng hàng hóa đơn', 45),
  ('orders.cancel', 'orders.cancel', 'orders', 'cancel', 'Hủy hóa đơn đã chốt', 'Đơn hàng', 'Hủy hóa đơn sau khi đã chốt (quyền nhạy cảm)', 46),
  ('orders.delete', 'orders.delete', 'orders', 'delete', 'Xóa hóa đơn', 'Đơn hàng', 'Xóa cứng hóa đơn khỏi hệ thống (quyền nhạy cảm)', 47),
  ('orders.refund', 'orders.refund', 'orders', 'refund', 'Hoàn tiền hóa đơn', 'Đơn hàng', 'Tạo phiếu hoàn tiền cho hóa đơn đã chốt', 48),
  ('orders.discount.approve', 'orders.discount.approve', 'orders', 'discount.approve', 'Duyệt giảm giá hóa đơn', 'Đơn hàng', 'Phê duyệt giảm giá vượt ngưỡng trên hóa đơn', 49),
  ('orders.print', 'orders.print', 'orders', 'print', 'In / tải hóa đơn', 'Đơn hàng', 'In lại hoặc tải PDF hóa đơn', 50),
  ('orders.export', 'orders.export', 'orders', 'export', 'Xuất danh sách hóa đơn', 'Đơn hàng', 'Xuất hóa đơn ra file Excel/CSV', 51),
  ('returns.view', 'returns.view', 'returns', 'view', 'Xem phiếu trả hàng', 'Trả hàng', 'Xem danh sách phiếu trả hàng', 52),
  ('returns.create', 'returns.create', 'returns', 'create', 'Tạo phiếu trả hàng', 'Trả hàng', 'Khởi tạo phiếu trả hàng từ khách', 53),
  ('returns.update', 'returns.update', 'returns', 'update', 'Cập nhật phiếu trả', 'Trả hàng', 'Chỉnh sửa thông tin / dòng hàng trên phiếu trả', 54),
  ('returns.approve', 'returns.approve', 'returns', 'approve', 'Duyệt phiếu trả hàng', 'Trả hàng', 'Phê duyệt phiếu trả hàng', 55),
  ('returns.refund', 'returns.refund', 'returns', 'refund', 'Hoàn tiền cho khách', 'Trả hàng', 'Ghi nhận hoàn tiền cho phiếu trả', 56),
  ('customers.view', 'customers.view', 'customers', 'view', 'Xem khách hàng', 'Khách hàng', 'Xem danh sách khách hàng', 57),
  ('customers.detail.view', 'customers.detail.view', 'customers', 'detail.view', 'Xem chi tiết khách hàng', 'Khách hàng', 'Xem hồ sơ chi tiết của một khách hàng', 58),
  ('customers.create', 'customers.create', 'customers', 'create', 'Thêm khách hàng', 'Khách hàng', 'Tạo hồ sơ khách hàng mới', 59),
  ('customers.update', 'customers.update', 'customers', 'update', 'Cập nhật khách hàng', 'Khách hàng', 'Chỉnh sửa thông tin khách hàng', 60),
  ('customers.delete', 'customers.delete', 'customers', 'delete', 'Xóa khách hàng', 'Khách hàng', 'Xóa hồ sơ khách hàng khỏi hệ thống', 61),
  ('customers.merge', 'customers.merge', 'customers', 'merge', 'Gộp khách hàng trùng', 'Khách hàng', 'Hợp nhất các hồ sơ khách hàng bị trùng', 62),
  ('customers.import', 'customers.import', 'customers', 'import', 'Nhập khách hàng từ Excel', 'Khách hàng', 'Tải lên file để thêm khách hàng hàng loạt', 63),
  ('customers.export', 'customers.export', 'customers', 'export', 'Xuất khách hàng ra Excel', 'Khách hàng', 'Xuất danh sách khách hàng ra file', 64),
  ('customers.debt.view', 'customers.debt.view', 'customers', 'debt.view', 'Xem công nợ khách hàng', 'Khách hàng', 'Xem số dư công nợ của từng khách hàng', 65),
  ('customers.debt.collect', 'customers.debt.collect', 'customers', 'debt.collect', 'Thu công nợ khách hàng', 'Khách hàng', 'Ghi nhận thu nợ từ khách hàng', 66),
  ('suppliers.view', 'suppliers.view', 'suppliers', 'view', 'Xem nhà cung cấp', 'Nhà cung cấp', 'Xem danh sách nhà cung cấp', 67),
  ('suppliers.create', 'suppliers.create', 'suppliers', 'create', 'Thêm nhà cung cấp', 'Nhà cung cấp', 'Tạo hồ sơ nhà cung cấp mới', 68),
  ('suppliers.update', 'suppliers.update', 'suppliers', 'update', 'Cập nhật nhà cung cấp', 'Nhà cung cấp', 'Chỉnh sửa thông tin nhà cung cấp', 69),
  ('suppliers.delete', 'suppliers.delete', 'suppliers', 'delete', 'Xóa nhà cung cấp', 'Nhà cung cấp', 'Xóa hồ sơ nhà cung cấp', 70),
  ('suppliers.debt.view', 'suppliers.debt.view', 'suppliers', 'debt.view', 'Xem công nợ NCC', 'Nhà cung cấp', 'Xem số dư công nợ với nhà cung cấp', 71),
  ('suppliers.debt.pay', 'suppliers.debt.pay', 'suppliers', 'debt.pay', 'Thanh toán công nợ NCC', 'Nhà cung cấp', 'Ghi nhận thanh toán cho nhà cung cấp', 72),
  ('purchases.view', 'purchases.view', 'purchases', 'view', 'Xem đơn nhập hàng', 'Nhập hàng', 'Xem danh sách đơn đặt hàng nhập', 73),
  ('purchases.create', 'purchases.create', 'purchases', 'create', 'Tạo đơn nhập hàng', 'Nhập hàng', 'Tạo đơn đặt hàng từ nhà cung cấp', 74),
  ('purchases.update', 'purchases.update', 'purchases', 'update', 'Cập nhật đơn nhập', 'Nhập hàng', 'Chỉnh sửa đơn nhập trước khi nhận hàng', 75),
  ('purchases.delete', 'purchases.delete', 'purchases', 'delete', 'Xóa đơn nhập', 'Nhập hàng', 'Xóa đơn nhập khỏi hệ thống', 76),
  ('purchases.receive', 'purchases.receive', 'purchases', 'receive', 'Nhận hàng / nhập kho', 'Nhập hàng', 'Xác nhận đã nhận hàng và nhập vào kho', 77),
  ('purchases.cancel', 'purchases.cancel', 'purchases', 'cancel', 'Hủy đơn nhập', 'Nhập hàng', 'Hủy đơn nhập đã tạo', 78),
  ('purchases.return', 'purchases.return', 'purchases', 'return', 'Trả hàng cho NCC', 'Nhập hàng', 'Tạo phiếu trả hàng cho nhà cung cấp', 79),
  ('purchases.approve', 'purchases.approve', 'purchases', 'approve', 'Duyệt đơn nhập', 'Nhập hàng', 'Phê duyệt đơn nhập trước khi đặt hàng NCC', 80),
  ('finance.overview.view', 'finance.overview.view', 'finance', 'overview.view', 'Xem tổng quan tài chính', 'Tài chính', 'Truy cập trang tổng quan tài chính', 81),
  ('finance.cashflow.view', 'finance.cashflow.view', 'finance', 'cashflow.view', 'Xem dòng tiền', 'Tài chính', 'Xem báo cáo dòng tiền vào / ra', 82),
  ('finance.cashflow.create', 'finance.cashflow.create', 'finance', 'cashflow.create', 'Ghi nhận giao dịch dòng tiền', 'Tài chính', 'Tạo bản ghi thu / chi vào dòng tiền', 83),
  ('finance.expenses.view', 'finance.expenses.view', 'finance', 'expenses.view', 'Xem chi phí', 'Tài chính', 'Xem danh sách chi phí của doanh nghiệp', 84),
  ('finance.expenses.create', 'finance.expenses.create', 'finance', 'expenses.create', 'Ghi nhận chi phí', 'Tài chính', 'Thêm chi phí phát sinh mới', 85),
  ('finance.expenses.delete', 'finance.expenses.delete', 'finance', 'expenses.delete', 'Xóa chi phí', 'Tài chính', 'Xóa bản ghi chi phí (quyền nhạy cảm)', 86),
  ('finance.recurring.view', 'finance.recurring.view', 'finance', 'recurring.view', 'Xem chi phí định kỳ', 'Tài chính', 'Xem các khoản chi phí định kỳ tự động', 87),
  ('finance.recurring.manage', 'finance.recurring.manage', 'finance', 'recurring.manage', 'Quản lý chi phí định kỳ', 'Tài chính', 'Tạo / cập nhật / xóa khoản chi phí định kỳ', 88),
  ('finance.profit.view', 'finance.profit.view', 'finance', 'profit.view', 'Xem lợi nhuận', 'Tài chính', 'Truy cập báo cáo lợi nhuận & lỗ (quyền nhạy cảm)', 89),
  ('finance.payroll.view', 'finance.payroll.view', 'finance', 'payroll.view', 'Xem bảng lương', 'Tài chính', 'Xem bảng lương nhân viên (quyền nhạy cảm)', 90),
  ('finance.payroll.manage', 'finance.payroll.manage', 'finance', 'payroll.manage', 'Quản lý bảng lương', 'Tài chính', 'Tạo và chốt bảng lương nhân viên', 91),
  ('finance.bank_accounts.manage', 'finance.bank_accounts.manage', 'finance', 'bank_accounts.manage', 'Quản lý tài khoản ngân hàng', 'Tài chính', 'Thêm / sửa / xóa tài khoản ngân hàng nhận tiền', 92),
  ('debt.view', 'debt.view', 'debt', 'view', 'Xem công nợ', 'Công nợ', 'Truy cập trang quản lý công nợ', 93),
  ('debt.create', 'debt.create', 'debt', 'create', 'Ghi nhận công nợ', 'Công nợ', 'Tạo phiếu công nợ mới', 94),
  ('debt.collect', 'debt.collect', 'debt', 'collect', 'Thu công nợ', 'Công nợ', 'Ghi nhận thu / trả công nợ', 95),
  ('debt.write_off', 'debt.write_off', 'debt', 'write_off', 'Xóa nợ', 'Công nợ', 'Xóa nợ khó đòi (quyền nhạy cảm)', 96),
  ('einvoice.view', 'einvoice.view', 'einvoice', 'view', 'Xem hóa đơn điện tử', 'Hóa đơn điện tử', 'Xem danh sách hóa đơn điện tử đã phát hành', 97),
  ('einvoice.issue', 'einvoice.issue', 'einvoice', 'issue', 'Phát hành hóa đơn điện tử', 'Hóa đơn điện tử', 'Phát hành hóa đơn điện tử cho khách hàng', 98),
  ('einvoice.configure', 'einvoice.configure', 'einvoice', 'configure', 'Cấu hình hóa đơn điện tử', 'Hóa đơn điện tử', 'Cấu hình kết nối nhà cung cấp HĐĐT', 99),
  ('payments.view', 'payments.view', 'payments', 'view', 'Xem giao dịch thanh toán', 'Thanh toán VietQR', 'Xem lịch sử giao dịch chuyển khoản / VietQR', 100),
  ('payments.refund', 'payments.refund', 'payments', 'refund', 'Hoàn tiền giao dịch', 'Thanh toán VietQR', 'Ghi nhận hoàn tiền cho giao dịch VietQR', 101),
  ('payments.configure', 'payments.configure', 'payments', 'configure', 'Cấu hình cổng thanh toán', 'Thanh toán VietQR', 'Thiết lập tài khoản nhận VietQR / webhook', 102),
  ('reports.dashboard.view', 'reports.dashboard.view', 'reports', 'dashboard.view', 'Báo cáo tổng quan', 'Báo cáo', 'Báo cáo doanh thu / hoạt động tổng hợp', 103),
  ('reports.sales.view', 'reports.sales.view', 'reports', 'sales.view', 'Báo cáo bán hàng', 'Báo cáo', 'Báo cáo chi tiết doanh thu, sản phẩm bán chạy', 104),
  ('reports.product.view', 'reports.product.view', 'reports', 'product.view', 'Báo cáo sản phẩm', 'Báo cáo', 'Báo cáo tồn kho, sản phẩm theo thời gian', 105),
  ('reports.inventory.view', 'reports.inventory.view', 'reports', 'inventory.view', 'Báo cáo kho', 'Báo cáo', 'Báo cáo nhập / xuất / tồn kho chi tiết', 106),
  ('reports.staff.view', 'reports.staff.view', 'reports', 'staff.view', 'Báo cáo nhân viên', 'Báo cáo', 'Báo cáo doanh số theo nhân viên', 107),
  ('reports.export', 'reports.export', 'reports', 'export', 'Xuất báo cáo', 'Báo cáo', 'Xuất file PDF / Excel cho mọi báo cáo', 108),
  ('staff.view', 'staff.view', 'staff', 'view', 'Xem nhân viên', 'Nhân viên', 'Xem danh sách nhân viên trong tổ chức', 109),
  ('staff.create', 'staff.create', 'staff', 'create', 'Tạo nhân viên', 'Nhân viên', 'Cấp tài khoản đăng nhập cho nhân viên mới', 110),
  ('staff.update', 'staff.update', 'staff', 'update', 'Cập nhật nhân viên', 'Nhân viên', 'Chỉnh sửa thông tin nhân viên', 111),
  ('staff.deactivate', 'staff.deactivate', 'staff', 'deactivate', 'Khóa nhân viên', 'Nhân viên', 'Tạm ngưng / khóa tài khoản nhân viên', 112),
  ('staff.assign_role', 'staff.assign_role', 'staff', 'assign_role', 'Gán vai trò', 'Nhân viên', 'Gán vai trò truy cập cho nhân viên', 113),
  ('staff.permissions.manage', 'staff.permissions.manage', 'staff', 'permissions.manage', 'Quản lý phân quyền', 'Nhân viên', 'Tạo vai trò tùy chỉnh và gán quyền hạn (chỉ Owner)', 114),
  ('roles.view', 'roles.view', 'roles', 'view', 'Xem vai trò', 'Vai trò & Phân quyền', 'Xem danh sách vai trò và ma trận quyền', 115),
  ('roles.create', 'roles.create', 'roles', 'create', 'Tạo vai trò', 'Vai trò & Phân quyền', 'Tạo vai trò mới cho tổ chức', 116),
  ('roles.update', 'roles.update', 'roles', 'update', 'Cập nhật vai trò', 'Vai trò & Phân quyền', 'Đổi tên, mô tả và cấu hình vai trò', 117),
  ('roles.delete', 'roles.delete', 'roles', 'delete', 'Xóa vai trò', 'Vai trò & Phân quyền', 'Xóa vai trò tùy chỉnh khỏi tổ chức', 118),
  ('roles.manage', 'roles.manage', 'roles', 'manage', 'Quản lý ma trận phân quyền', 'Vai trò & Phân quyền', 'Tick/untick và lưu quyền cho các vai trò', 119),
  ('loyalty.view', 'loyalty.view', 'loyalty', 'view', 'Xem cấu hình tích điểm', 'Tích điểm & Loyalty', 'Xem quy tắc tích điểm và lịch sử điểm khách hàng', 120),
  ('loyalty.configure', 'loyalty.configure', 'loyalty', 'configure', 'Cấu hình tích điểm', 'Tích điểm & Loyalty', 'Thiết lập quy tắc tích / đổi điểm, hạng thành viên', 121),
  ('loyalty.redeem', 'loyalty.redeem', 'loyalty', 'redeem', 'Đổi điểm thanh toán', 'Tích điểm & Loyalty', 'Áp dụng điểm tích lũy để thanh toán đơn hàng', 122),
  ('loyalty.adjust', 'loyalty.adjust', 'loyalty', 'adjust', 'Điều chỉnh điểm thủ công', 'Tích điểm & Loyalty', 'Cộng / trừ điểm khách hàng thủ công kèm lý do', 123),
  ('loyalty.campaign.manage', 'loyalty.campaign.manage', 'loyalty', 'campaign.manage', 'Quản lý chiến dịch loyalty', 'Tích điểm & Loyalty', 'Tạo và quản lý chiến dịch khuyến mãi tích điểm', 124),
  ('zalo.view', 'zalo.view', 'zalo', 'view', 'Xem tin nhắn Zalo', 'Tin nhắn Zalo', 'Xem lịch sử tin nhắn với khách qua Zalo', 125),
  ('zalo.send', 'zalo.send', 'zalo', 'send', 'Gửi tin nhắn Zalo', 'Tin nhắn Zalo', 'Gửi tin nhắn chăm sóc khách qua Zalo', 126),
  ('zalo.configure', 'zalo.configure', 'zalo', 'configure', 'Cấu hình Zalo OA', 'Tin nhắn Zalo', 'Cấu hình kết nối Zalo Official Account', 127),
  ('ai.chat', 'ai.chat', 'ai', 'chat', 'Sử dụng trợ lý AI Chat', 'Trợ lý AI', 'Trò chuyện với trợ lý AI để hỏi đáp vận hành', 128),
  ('ai.voice', 'ai.voice', 'ai', 'voice', 'Sử dụng trợ lý giọng nói', 'Trợ lý AI', 'Sử dụng AI giọng nói (TTS) trong cửa hàng', 129),
  ('ai.product_image', 'ai.product_image', 'ai', 'product_image', 'Tạo ảnh sản phẩm bằng AI', 'Trợ lý AI', 'Sinh ảnh sản phẩm tự động bằng AI', 130),
  ('sync.view', 'sync.view', 'sync', 'view', 'Xem trạng thái đồng bộ', 'Đồng bộ offline', 'Xem trạng thái đồng bộ giữa thiết bị và server', 131),
  ('sync.manage', 'sync.manage', 'sync', 'manage', 'Điều khiển đồng bộ offline', 'Đồng bộ offline', 'Kích hoạt / dừng / xử lý xung đột đồng bộ', 132),
  ('settings.business.view', 'settings.business.view', 'settings', 'business.view', 'Xem thông tin doanh nghiệp', 'Cài đặt', 'Xem thông tin chung của doanh nghiệp / cửa hàng', 133),
  ('settings.business.update', 'settings.business.update', 'settings', 'business.update', 'Cập nhật thông tin doanh nghiệp', 'Cài đặt', 'Chỉnh sửa thông tin, logo, mã số thuế', 134),
  ('settings.branches.manage', 'settings.branches.manage', 'settings', 'branches.manage', 'Quản lý chi nhánh', 'Cài đặt', 'Tạo / sửa / xóa chi nhánh, quầy thu ngân', 135),
  ('settings.branch.update', 'settings.branch.update', 'settings', 'branch.update', 'Cập nhật chi nhánh', 'Cài đặt', 'Cập nhật cấu hình chi nhánh', 136),
  ('settings.printers.manage', 'settings.printers.manage', 'settings', 'printers.manage', 'Cấu hình máy in', 'Cài đặt', 'Cấu hình máy in hóa đơn, máy in bếp', 137),
  ('settings.printer.update', 'settings.printer.update', 'settings', 'printer.update', 'Cập nhật máy in', 'Cài đặt', 'Cập nhật cấu hình máy in', 138),
  ('settings.billing.update', 'settings.billing.update', 'settings', 'billing.update', 'Cập nhật thanh toán & gói dịch vụ', 'Cài đặt', 'Cập nhật cấu hình thanh toán, hóa đơn và gói dịch vụ', 139),
  ('settings.tax.manage', 'settings.tax.manage', 'settings', 'tax.manage', 'Cấu hình thuế suất', 'Cài đặt', 'Thiết lập thuế suất và quy tắc tính thuế', 140),
  ('settings.payments.manage', 'settings.payments.manage', 'settings', 'payments.manage', 'Cấu hình phương thức thanh toán', 'Cài đặt', 'Thiết lập phương thức thanh toán & ngân hàng', 141),
  ('settings.security.manage', 'settings.security.manage', 'settings', 'security.manage', 'Cấu hình bảo mật', 'Cài đặt', 'Cấu hình 2FA, giới hạn IP, chính sách mật khẩu', 142),
  ('settings.integrations.manage', 'settings.integrations.manage', 'settings', 'integrations.manage', 'Quản lý tích hợp', 'Cài đặt', 'Cấu hình tích hợp với bên thứ ba (Telegram, GHN, GHTK…)', 143),
  ('audit.view', 'audit.view', 'audit', 'view', 'Xem nhật ký hoạt động', 'Nhật ký & Bảo mật', 'Xem audit log toàn hệ thống', 144),
  ('audit.export', 'audit.export', 'audit', 'export', 'Xuất nhật ký hoạt động', 'Nhật ký & Bảo mật', 'Xuất audit log ra file để báo cáo / compliance', 145),
  ('security.sessions.manage', 'security.sessions.manage', 'security', 'sessions.manage', 'Quản lý phiên đăng nhập', 'Nhật ký & Bảo mật', 'Xem và đóng phiên đăng nhập đang hoạt động', 146)
on conflict (id) do update set
  key = excluded.key,
  module = excluded.module,
  action = excluded.action,
  name = excluded.name,
  group_name = excluded.group_name,
  description = excluded.description,
  sort_order = excluded.sort_order;
